k8s_nginx:
  ports:
  - 8080:80/tcp
  image: nginx:alpine
  volumes:
  - ./nginx.conf:/etc/nginx/nginx.conf:ro
  - ./k8s.conf:/etc/nginx/conf.d/default.conf:ro



#docker run --net=host -d -P -v /root/k8s.conf:/etc/nginx/conf.d/default.conf:ro nginx
