---

- name: set timezone to shanghai
  shell: sudo cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime


- name: prepare some dirs
  file: name={{ item }} state=directory
  with_items:
  - "{{ bin_dir }}"
  - "{{ ca_dir }}"
  - /root/.kube
  - /etc/docker

- name: copy /etc/yum.repos.d/CentOS-Base.repo
  copy: src=Centos-7.repo dest=/etc/yum.repos.d/CentOS-Base.repo

#- name: copy docker-ce.repo to /etc/yum.repos.d/docker-ce.repo
#  shell: sudo curl -o /etc/yum.repos.d/docker-ce.repo http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo

#- name: 集群hosts文件更新
#  copy: src=hosts.j2 dest=/etc/hosts

- name: 写入环境变量$PATH 
  shell: "sed -i '/export PATH=/d' /etc/profile && \
	echo export PATH={{ bin_dir }}:$PATH >> /etc/profile"

- name: 下载证书工具 CFSSL
  copy: src={{ base_dir }}/bin/cfssl/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
  with_items:
  - cfssl
  - cfssl-certinfo
  - cfssljson

- name: 分发CA 证书
  copy: src={{ item }} dest={{ ca_dir }}/{{ item }} mode=0644
  with_items:
  - ca.pem
  - ca-key.pem
  - ca.csr
  - ca-config.json

# 先拉取下节点的ansible setup信息，起到缓存效果，否则后续when 判断可能失败
- name: 缓存ansilbe setup信息
  setup: gather_subset=min

# 删除默认安装
- name: 删除ubuntu默认安装
  apt: name={{ item }} state=absent
  with_items:
  - ufw
  - lxd
  - lxd-client
  - lxcfs
  - lxc-common
  when: ansible_distribution == "Ubuntu"

# 删除默认安装
- name: 删除centos默认安装
  yum: name={{ item }} state=absent
  with_items:
  - firewalld
  - firewalld-filesystem
  - python-firewall
  when: ansible_distribution == "CentOS"

- name: 关闭 selinux in /etc/selinux/config 
  # shell: "setenforce 0 && echo SELINUX=disabled > /etc/selinux/config"
  shell: "setenforce 0 && sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config"
  # copy:
  #   content: |
  #     SELINUX=disabled
  #     SELINUXTYPE=targeted
  #   dest: /etc/selinux/config
  when: ansible_distribution == "CentOS"
  ignore_errors: true

# 设置系统参数for k8s
# 消除docker info 警告WARNING: bridge-nf-call-ip[6]tables is disabled
- name: 设置系统参数
  copy: src=95-k8s-sysctl.conf dest=/etc/sysctl.d/95-k8s-sysctl.conf

- name: 加载br_netfilter模块
  modprobe: name=br_netfilter state=present
  #shell: "modprobe br_netfilter"
  
- name: 生效系统参数
  shell: "sysctl -p /etc/sysctl.d/95-k8s-sysctl.conf"
  ignore_errors: true
# - name: enable ip forward
#   sysctl: name={{ item }} value=1 state=present reload=yes sysctl_file=/etc/sysctl.d/k8s.conf
#   with_items:
#     - net.ipv4.conf.all.forwarding
#     - net.ipv6.conf.all.forwarding
#     - net.bridge.bridge-nf-call-ip6tables
#     - net.bridge.bridge-nf-call-iptables
#     - net.bridge.bridge-nf-call-arptables

# - name: disable vm swappiness
#   sysctl: name={{ item }} value=0 state=present reload=yes sysctl_file=/etc/sysctl.d/k8s.conf
#   with_items:
#     - vm.swappiness
- name: copy /etc/sysctl.d/k8s.conf
  copy:
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-arptables = 1
      net.ipv4.conf.all.forwarding = 1
      net.ipv6.conf.all.forwarding = 1
      net.ipv4.ip_forward = 1
      vm.swappiness=0
    dest: /etc/sysctl.d/k8s.conf

- name: sysctl sync
  shell: sysctl -p /etc/sysctl.d/k8s.conf; sysctl --system
